services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: garlic-hub
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:80"
    volumes:
      - ./data/public:/var/www/public/var
      - ./data/var:/var/www/var
